OCD-3392: Send user an email when their account is locked.
chpladmin/chpl-api pull request #1015
Opened 2020-09-03 19:20 UTC by kekey1

2020-09-08 19:21 UTC, andlar requested changes

2020-09-08 19:21 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/auth/UserManager.java
> +        if (userToUpdate.getFailedLoginCount() == maxLogins) {
I know it's unlikely, but if something happened where the failed login count jumped over the maxLogins value, and somehow didn't actually lock the account, then we never would, right? Can we keep this comparison as `>=` and add a separate `if` inside this block to send the email only when the `==` comparison is true?

2020-09-09 14:03 UTC, andlar submitted a review, later dismissed

2020-09-10 16:24 UTC, tmy1313 approved these changes, later dismissed

2020-09-10 16:24 UTC, tmy1313 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/AuthenticationController.java
> +                + "</pre>";
This should be moved to the email.properties file.

2020-09-10 17:17 UTC, andlar submitted a review, later dismissed

2020-09-11 14:50 UTC, andlar submitted a review, later dismissed

2020-09-16 14:55 UTC, andlar approved these changes

2020-09-16 18:29 UTC, tmy1313 approved these changes

2020-09-16 18:35 UTC, merged