[#OCD-3410] feat!: Make "username" not required for new users
chpladmin/chpl-api pull request #1043
Opened 2020-11-10 15:21 UTC by andlar

2020-11-12 11:59 UTC, kekey1 requested changes
I had a few small things to be changed in the code. In doing a search of the code for where getSubjectName() is referenced, I would like to ask if you have tested/there are test cases for the following: 
- Performing questionable activity as a user with email only (NULL username) and scheduling the job to send the email. Receive the email and look in it to make sure the data is filled in right. (existing code puts in the username to the report)
- Doing some kind of edit of a user without a username and viewing activity reports
- Viewing any activity report when the activity was performed by a user without a username
- Uploading a surveillance file with more than <threshold for background job> records when the user doesn't have permissions on the ACB that owns the listings in the file (obscure I know but I see subject name referenced in an error message there)

2020-11-12 11:59 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/AuthenticationController.java
>      @ApiOperation(value = "Impersonate another user.", notes = "")
Can you add "DEPRECATED" to the text here? Done in a few other controllers with deprecated methods

2020-11-12 11:59 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/UserManagementController.java
>      @ApiOperation(value = "View a specific user's details.",
Add "DEPRECATED" to text

2020-11-12 11:59 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/auth/jwt/JWTConsumer.java
> +    Map<String, Object> consume(String jwt) throws InvalidJwtException;
I feel like this interface and the JWTAuthor interfaces are instances in which we can get rid of the interfaces (like we have been doing with the DAO and DAOImpl, Manager and ManagerImpl, etc. code). If there is no other class that implements these interfaces I *think* we don't need them; the interfaces could be deleted and the implementing class could be renamed to JWTConsumer

2020-11-12 11:59 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/auth/UserDAO.java
> +    private UserEntity getEntityByNameOrEmail(String email) throws MultipleUserAccountsException, UserRetrievalException {
I think the addition of this method means there are now two methods in this class with essentially the same HQL. Can you make the one that returns the DTO call this method so the HQL is only in one place?

2020-11-12 18:40 UTC, kekey1 submitted a review, later dismissed

2020-11-12 19:51 UTC, tmy1313 submitted a review, later dismissed

2020-12-07 18:11 UTC, kekey1 approved these changes

2020-12-08 17:18 UTC, tmy1313 approved these changes

2020-12-08 17:21 UTC, merged