OCD-3401: Add direct reviews to collections endpoint
chpladmin/chpl-api pull request #1072
Opened 2021-02-01 16:36 UTC by kekey1

2021-02-02 13:08 UTC, andlar submitted a review, later dismissed

2021-02-02 13:08 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/CertifiedProductSearchDAO.java
> +        for (CertifiedProductBasicSearchResultEntity dbResult : dbResults) {
Would this be a candidate for a stream -> builder thing?

2021-02-02 18:12 UTC, tmy1313 requested changes

2021-02-02 18:12 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/search/CertifiedProductBasicSearchResult.java
> +public class CertifiedProductBasicSearchResult extends CertifiedProductSearchResultLegacy {
Should we be extending a `@Deprecated` class?  I'm not sure...  Are we still using the `CertifiedProductSearchResultLegacy` ? Should `CertifiedProductSearchResultLegacy` maybe be abstract? I'm not sure what the right answer is here off the top of my head.

2021-02-02 18:12 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/CertifiedProductSearchManager.java
> +            && nc.getNonConformityStatus().equalsIgnoreCase(nonConformityStatus))
Do we have an indentation standard?  I thought it was 2 tabs (or 8 spaces).  I see that is what is done below.

2021-02-03 14:39 UTC, tmy1313 approved these changes, later dismissed

2021-02-03 14:46 UTC, andlar approved these changes, later dismissed

2021-02-10 19:53 UTC, andlar approved these changes

2021-02-10 20:24 UTC, tmy1313 approved these changes

2021-02-10 23:51 UTC, merged