Ocd 3581- Add G1-G2 measures to basic API endpoints
chpladmin/chpl-api pull request #1091
Opened 2021-03-05 19:25 UTC by tmy1313

2021-03-06 15:15 UTC, andlar requested changes

2021-03-06 15:15 UTC, andlar commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CertifiedProductController.java
> +            notes = "Returns all of the CQM results in the CHPL related to the specified certified product.")
This documentation doesn't match the name of the function

2021-03-06 15:15 UTC, andlar commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CertifiedProductController.java
>              + "the CQM results and certification results.",
Should also mention that we're excluding measures. Or maybe try to make it generic and say something about "does not include elements that are in other "non-/details" endpoints"

2021-03-08 15:12 UTC, kekey1 approved these changes, later dismissed

2021-03-08 15:42 UTC, andlar approved these changes

2021-03-08 15:45 UTC, kekey1 approved these changes

2021-03-18 16:49 UTC, merged