feat: remove g1/g2 data fix job
chpladmin/chpl-api pull request #1095
Opened 2021-03-17 14:48 UTC by tmy1313

OCD-3580

2021-03-17 15:01 UTC, andlar requested changes

2021-03-17 15:01 UTC, andlar commented on chpl/chpl-resources/src/main/resources/jobs.xml
> +        <delete-job>
There were some loggers added as part of the initial PR. Those ought to be removed in this PR as well, right?

2021-03-19 14:23 UTC, andlar approved these changes

2021-03-19 16:19 UTC, kekey1 approved these changes

2021-03-25 03:20 UTC, closed without merging

2021-03-25 03:20 UTC, tmy1313 commented
This has been moved to OCD-3639