OCD-3534 - Ability to create Surveillance Activity Report as Excel spreadsheet
chpladmin/chpl-api pull request #1119
Opened 2021-05-10 16:44 UTC by tmy1313

2021-05-11 01:05 UTC, kekey1 requested changes

2021-05-11 01:05 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/SurveillanceController.java
> +            throw new ValidationException("Could not parse the start and/or end date.  The correct format is 'yyyy-mm-dd'.");
Move to errors.properties?

2021-05-11 01:05 UTC, kekey1 commented on chpl/chpl-resources/src/main/resources-dev/quartz.properties
> +org.quartz.scheduler.jmx.export = true
Can you just explain this change? Related to DataDog?

2021-05-11 01:05 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/surveillance/ActivityReportActionPermission.java
> +       return getResourcePermissions().isUserRoleAdmin() || getResourcePermissions().isUserRoleOnc();
This says ADMIN or ONC but the jobs.xml file says ADMIN or ACB

2021-05-11 01:05 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/surveillancereportingactivity/SurveillanceActivityReportDataGatherer.java
> +    @Autowired
Use Autowired constructor instead

2021-05-11 03:09 UTC, tmy1313 commented on chpl/chpl-resources/src/main/resources-dev/quartz.properties
> +org.quartz.scheduler.jmx.export = true
Yes - I'm going to move this to the Datadog ticket.

2021-05-11 13:36 UTC, kekey1 approved these changes, later dismissed

2021-05-11 14:59 UTC, andlar commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/SurveillanceController.java
> +import gov.healthit.chpl.web.controller.results.BooleanResult;
Is checkstyle right about the unused import?

2021-05-11 14:59 UTC, andlar commented on chpl/chpl-resources/src/main/resources/jobs.xml
> +                    <value>ROLE_ADMIN;ROLE_ONC</value>
This should have `ROLE_ONC_STAFF`, right?

2021-05-11 14:59 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/surveillancereportingactivity/Statistics.java
> +    public static Integer getMinimum(List<Integer> values) {
Do we need this? Or can something in the Collections package do this without rolling our own?

2021-05-11 14:59 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/surveillancereportingactivity/charts/ClosedSurveillanceDurationByQuartileChart.java
> +            //plot.setOrientation(PlotOrientation.HORIZONTAL);
Still needed?

2021-05-13 00:50 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/surveillancereportingactivity/Statistics.java
> +    public static Integer getMinimum(List<Integer> values) {
There is a possibility of there being null values in the list and this function handles them.

2021-05-13 00:59 UTC, tmy1313 commented on chpl/chpl-resources/src/main/resources/jobs.xml
> +                    <value>ROLE_ADMIN;ROLE_ONC</value>
I added it, but I don't think it does anything.  The purpose of the `authorities` in the job definition is so the front end "knows" which jobs a particular user can run/schedule.   For `chplBackGroundJobs` which are generally called by managers, the security resides in the manager.

2021-05-13 10:38 UTC, kekey1 submitted a review, later dismissed

2021-05-13 11:38 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/surveillance/ActivityReportActionPermission.java
> +       return getResourcePermissions().isUserRoleAdmin() || getResourcePermissions().isUserRoleOnc();
I thought we said, at the FR, that this job would be available for ROLE_ONC_STAFF, even if the UI doesn't give them a way to run it yet. This looks like it's not available

2021-05-13 11:38 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/surveillancereportingactivity/excel/CellHelper.java
> +public class CellHelper {
Do we care about these checkstyle issues? I think there was one here as well as one in one of the XML files

2021-05-13 16:21 UTC, andlar submitted a review, later dismissed

2021-05-13 17:05 UTC, kekey1 submitted a review, later dismissed

2021-06-11 15:57 UTC, andlar approved these changes, later dismissed

2021-06-21 13:35 UTC, kekey1 approved these changes, later dismissed

2021-06-21 14:19 UTC, kekey1 approved these changes

2021-06-21 15:00 UTC, andlar approved these changes

2021-06-21 17:48 UTC, merged