docs: update README.md to more closely reflect current state of CHPL
chpladmin/chpl-api pull request #1124
Opened 2021-05-24 15:50 UTC by tmy1313

OCD-3586

2021-05-24 16:40 UTC, andlar requested changes

2021-05-24 16:40 UTC, andlar commented on README.md
> +The following Proiperties Files exist within the CHPL Resources project.
```suggestion
The following Properties Files exist within the CHPL Resources project.
```

2021-05-24 16:40 UTC, andlar commented on README.md
>  Eclipse (latest)
```
* Java 1.8.0
* PostgreSQL 10.15
* mvn 3.3.3
* Tomcat 8.5.x --whatever the latest version is
* Eclipse (latest)

2021-05-24 16:40 UTC, andlar commented on README.md
> +| email.properties       | directReview.chplChanges.email     |                                                                                                   |
```suggestion
| File                   | Key                                | Description                                                                                       |
|---|---|---|
| email.properties       | directReview.chplChanges.email     |                                                                                                   |
```

2021-05-25 15:15 UTC, kekey1 requested changes

2021-05-25 15:15 UTC, kekey1 commented on README.md
> +| email.properties       | directReview.chplChanges.email     |                                                                                                   |
Email account to send notification of listing or developer changes that do affect direct reviews

2021-05-25 15:15 UTC, kekey1 commented on README.md
> +| email.properties       | directReviewunknownChanges.email   | Email address to be notified when changes are made to CHPL entities that possibley involve Direct Reviews    |
```suggestion
| email.properties       | directReviewunknownChanges.email   | Email address to be notified when changes are made to CHPL entities that possibly involve Direct Reviews    |
```

2021-05-26 13:37 UTC, kekey1 approved these changes, later dismissed

2021-05-26 13:43 UTC, andlar commented on README.md
> +Any value in the above files can be overridden by creating an "override" file.  The file should be name `originalFileName-override.properites` and be placed somewhere on the classpath.  In the "overr
```suggestion
Any value in the above files can be overridden by creating an "override" file.  The file should be name `originalFileName-override.properties` and be placed somewhere on the classpath.  In the "override" file, you can redefine any existing key with a new value.
```

2021-05-26 14:10 UTC, andlar approved these changes

2021-05-26 14:22 UTC, kekey1 approved these changes

2021-05-26 16:26 UTC, palakpatel311 approved these changes

2021-06-01 13:59 UTC, merged