Ocd 3637
chpladmin/chpl-api pull request #1129
Opened 2021-06-04 15:34 UTC by tmy1313

2021-06-07 13:19 UTC, kekey1 requested changes

2021-06-07 13:19 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/surveillance/CreateActionPermissions.java
> +        } else if (getResourcePermissions().isUserRoleAdmin()) {
The way I read the ticket it looks like ROLE_ONC should continue to be able to do stuff. Is that right?

2021-06-22 18:36 UTC, kekey1 approved these changes

2021-06-23 12:24 UTC, andlar approved these changes

2021-07-07 15:22 UTC, merged