OCD-3431: feat!: Disable Merge ability for ROLE_ACB
chpladmin/chpl-api pull request #1138
Opened 2021-06-16 13:00 UTC by andlar

2021-06-16 14:04 UTC, kekey1 requested changes
I think you also need to make a change to CreateBackgroundJobTriggerActionPermissions.... and the jobs.xml to not allow ACBs for the developer merge. Also, jobs.xml indicates ONC STAFF should be able to do it but I'm not sure the code in the permissions class matches that.

2021-06-16 16:51 UTC, kekey1 submitted a review, later dismissed

2021-06-16 17:06 UTC, kekey1 approved these changes

2021-07-07 15:25 UTC, tmy1313 approved these changes

2021-07-07 15:39 UTC, merged