OCD-3656 -Add header to all responses indicating prod/non-prod environment
chpladmin/chpl-api pull request #1142
Opened 2021-06-22 17:37 UTC by tmy1313

OCD-3656

2021-06-23 12:46 UTC, andlar reviewed
There's a checkstyle comment in the web.xml file

2021-06-23 12:46 UTC, andlar commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/filter/EnvironmentHeaderFilter.java
> +        String serverEnvironment = env.getProperty("server.environment") != null ? env.getProperty("server.environment") : "";
Do we need an update to one of the property files to put this key into it? Maybe the template file? I honestly don't remember where / how/ if we store property files in git anymore

2021-06-23 15:00 UTC, kekey1 requested changes

2021-06-28 19:31 UTC, kekey1 requested changes

2021-06-28 19:31 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/filter/EnvironmentHeaderFilter.java
> +    public EnvironmentHeaderFilter(@Value("${werver.environment}") String serverEnvironment) {
```suggestion
    public EnvironmentHeaderFilter(@Value("${server.environment}") String serverEnvironment) {
```

2021-06-29 13:37 UTC, kekey1 approved these changes

2021-06-29 13:56 UTC, andlar approved these changes

2021-07-06 14:02 UTC, merged