OCD-3716: AQA tests for ONC_STAFF permissions to activity, certificationId and searchView controllers
chpladmin/chpl-api pull request #1162
Opened 2021-08-04 17:59 UTC by athomas-git

OCD-3716: AQA tests for ONC_STAFF permissions to activity,certificationId and searchView controllers

2021-08-04 19:49 UTC, palakpatel311 requested changes

2021-08-04 19:49 UTC, palakpatel311 commented on chpl/chpl-api/e2e/collections/activity-controller.postman_collection.json
> +							"    const exprespbody = pm.response.json();\r",
Can we change "exprespbody" to be more meaningful name? As it is actual response body, name can eb something like actualResponseBody or actualBody

Similar comment to all requests below.

2021-08-04 20:04 UTC, palakpatel311 approved these changes

2021-08-09 14:38 UTC, tmy1313 approved these changes

2021-08-17 14:08 UTC, merged