OCD-3849 - Implement email try/resend feature
chpladmin/chpl-api pull request #1261
Opened 2022-02-07 17:04 UTC by tmy1313

2022-02-07 18:57 UTC, kekey1 requested changes

2022-02-07 18:57 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/AuthenticationController.java
> +    private ChplEmailFactory chplEmailFactory;
Could you move these fields into an Autowired constructor? Just as a refactor to keep up with our current coding style

2022-02-07 18:57 UTC, kekey1 commented on chpl/chpl-api/src/main/resources/log4j2-xinclude-file-appenders-json.xml
> +            <KeyValuePair key="dd.span_id" value="%X{dd.trace_id}" />
Curious about this line. I assume it was copy/pasted from elsewhere, but should the "dd.span_id" have a value of "dd.span_id" or is it correct that both fields have the value trace_id?

2022-02-07 18:57 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/email/ChplEmailFactory.java
> +    //private SchedulerManager schedulerManager;
Remove commented out references to schedulerManager

2022-02-07 18:57 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/SendEmailJob.java
> +        Path newPath = Paths.get(env.getProperty("downloadFolderPath") + File.separator + originalFile.getName());
Is this the directory we want to use? Or would we rather have a new and distinct folder we add to the machines that we use for this?

2022-02-09 18:26 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/SendEmailJob.java
> +        Path newPath = Paths.get(env.getProperty("downloadFolderPath") + File.separator + originalFile.getName());
I see this was changed but I wonder if you could make the folder name be a property or constant at least? Also will need a checklist item to create the directory for all environments.

2022-02-09 19:14 UTC, kekey1 submitted a review, later dismissed

2022-02-09 19:57 UTC, andlar approved these changes

2022-02-09 20:29 UTC, kekey1 approved these changes

2022-02-14 15:01 UTC, merged