OCD-3855: convert Announcements to have LocalDateTime
chpladmin/chpl-api pull request #1279
Opened 2022-03-29 14:59 UTC by andlar

2022-03-31 00:13 UTC, kekey1 approved these changes, later dismissed
Thanks for removing a DTO!

2022-03-31 00:13 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/Announcement.java
> +    public Announcement(AnnouncementEntity entity) {
Do we still need this constructor AND the toDomain method on the entity? Todd prefers the former and I prefer the latter but we really only need 1 as far as I know.

2022-03-31 00:13 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/activity/GetActivityDetailsActionPermissions.java
>              LOGGER.error("Could not parse announcement activity as AnnouncementDTO." + "JSON was: " + announcementJson,
Could you just change the log message to not say "AnnouncementDTO" as well? I know it's a small thing

2022-04-01 11:20 UTC, kekey1 submitted a review, later dismissed

2022-04-07 15:34 UTC, kekey1 submitted a review, later dismissed

2022-04-07 16:55 UTC, kekey1 submitted a review, later dismissed

2022-04-08 13:44 UTC, tmy1313 submitted a review, later dismissed

2022-04-08 13:44 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/AnnouncementManager.java
> +    private ActivityManager activityManager;
Before we go to STG - these @Autowired variable should be moved to a constructor.

2022-04-08 13:44 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/activity/GetActivityDetailsActionPermissions.java
> +    private static Logger LOGGER = LogManager.getLogger(GetActivityDetailsActionPermissions.class);
Could this be moved to an `@Log4j2` annotation at the class level?

2022-04-22 10:40 UTC, kekey1 approved these changes

2022-04-22 10:41 UTC, kekey1 requested changes
conflicts

2022-04-22 14:13 UTC, tmy1313 approved these changes

2022-04-22 14:17 UTC, kekey1 approved these changes

2022-04-25 18:48 UTC, merged