OCD-4057
chpladmin/chpl-api pull request #1368
Opened 2022-10-14 15:05 UTC by tmy1313

2022-10-14 15:56 UTC, kekey1 submitted a review, later dismissed

2022-10-14 16:32 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/questionableactivity/ListingQuestionableActivityService.java
> +import gov.healthit.chpl.questionableactivity.listing.NonActiveListingEdited;
This looks like the wrong name

2022-10-14 17:35 UTC, andlar approved these changes, later dismissed

2022-10-14 18:03 UTC, kekey1 approved these changes

2022-10-16 16:00 UTC, kekey1 requested changes

2022-10-16 16:00 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/Validator.java
> +        if (updatedListing.isCertificateActive()) {
I think this change is great for the 2015 listings. I just remembered I had hoped to change the 2014 validation to use the "AllowedListingValidator". Not recalling the name exactly but it's whatever we use for 2011 edition. There is a validator factory class which I believe assigns the correct validator to a listing. I was hoping to basically remove all references to 2014 edition listing validators in this PR and maybe, hopefully, delete those files.

2022-10-17 18:11 UTC, kekey1 requested changes

2022-10-17 18:11 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/ListingValidatorFactoryImpl.java
>  public class ListingValidatorFactoryImpl implements ListingValidatorFactory {
Left comment in chat - can we remove ListingValidatorFactory and make this one "not an Impl"?

2022-10-17 20:07 UTC, kekey1 approved these changes, later dismissed

2022-10-18 13:14 UTC, andlar submitted a review, later dismissed

2022-10-21 14:01 UTC, kekey1 approved these changes, later dismissed
I think it might be worth adding a test or two that expect this exception is thrown if you mock up a listing with some null test tool IDs or something.

2022-10-22 15:08 UTC, andlar approved these changes, later dismissed

2022-11-04 17:43 UTC, andlar commented on chpl/chpl-api/src/main/resources/log4j2-console.xml
> +        <Logger name="socks5bridge" level="TRACE" additivity="false">
Are these changes supposed to be in this PR?

2022-11-04 17:44 UTC, kekey1 requested changes

2022-11-04 17:44 UTC, kekey1 commented on chpl/chpl-api/src/main/resources/log4j2-console.xml
> +        <Logger name="javax.mail" level="TRACE" additivity="false">
Can you remove this?

2022-11-07 11:53 UTC, andlar submitted a review, later dismissed

2022-11-07 14:55 UTC, kekey1 approved these changes

2022-11-07 18:36 UTC, andlar approved these changes

2022-11-09 16:56 UTC, merged