OCD-4012 - Remove surveillance validation that checks to ensure listing is certified to selected criteria
chpladmin/chpl-api pull request #1396
Opened 2022-11-16 18:31 UTC by tmy1313

2022-11-16 18:41 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/surveillance/SurveillanceNonconformity.java
> -    @XmlElementWrapper(name = "documents", nillable = true, required = false)
Does this mean the ticket needs the "XSD-Impact" component?

2022-11-17 15:45 UTC, kekey1 approved these changes, later dismissed

2022-11-17 19:37 UTC, andlar approved these changes, later dismissed

2022-11-18 16:15 UTC, kekey1 approved these changes, later dismissed

2022-11-18 18:13 UTC, kekey1 submitted a review, later dismissed

2022-11-18 18:15 UTC, andlar approved these changes, later dismissed

2022-11-29 15:37 UTC, kekey1 requested changes

2022-11-29 15:37 UTC, kekey1 commented on chpl/chpl-api/src/test/java/gov/healthit/chpl/util/DeprecatedFieldExplorerTest.java
> +    public void findDeprecatedFields_SkipJsonIgnoreField_NotInResults() {
Reminder to annotate all the methods here with @ Test

2022-11-29 21:58 UTC, andlar approved these changes

2022-11-30 00:03 UTC, kekey1 approved these changes

2022-11-30 14:23 UTC, merged