OCD-4151 - RWT ICS Error showing up in wrong column in RWT Email Report
chpladmin/chpl-api pull request #1445
Opened 2023-02-09 21:38 UTC by tmy1313

OCD-4151

2023-02-09 22:18 UTC, kekey1 approved these changes, later dismissed

2023-02-10 13:44 UTC, andlar approved these changes

2023-02-10 13:44 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/realworldtesting/manager/RealWorldTestingReportService.java
> +                plansMessage =errorMsg.getMessage("realWorldTesting.report.eligibleByIcs.missingPlansError",
Checkstyle called this out, and I didn't want to approve it without doubling down on this. I'll approve the PR now, but want this changed before it gets merged
```suggestion
                plansMessage = errorMsg.getMessage("realWorldTesting.report.eligibleByIcs.missingPlansError",
```

2023-02-10 16:08 UTC, andlar requested changes
Calling out the comment

2023-02-22 16:45 UTC, closed without merging