OCD-4198 - Investigate ongoing issues with listing search endpoint under heavy usage
chpladmin/chpl-api pull request #1480
Opened 2023-04-20 16:09 UTC by tmy1313

2023-04-21 17:27 UTC, kekey1 requested changes

2023-04-21 17:27 UTC, kekey1 commented on chpl/chpl-api/src/main/resources/log4j2-xinclude-file-appenders-json.xml
> +        filePattern="${logDir}/scheduler/history/fixupQuestionableActivityJob-%d{yyyy-MM-dd}.json"
filePattern needs updated

2023-04-21 17:27 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/caching/ListingSearchCacheableAspect.java
> +    public Object logExecutionTime(ProceedingJoinPoint joinPoint) throws Throwable {
I'm not sure if I'm missing something or the method name is misleading? I don't see anything being logged, though it's called "logExecutionTime". 
I forgot why we need this annotation and we can't use the regular @ Cacheable annotation on the ListingSearchManager. Can you explain?

2023-04-24 16:17 UTC, kekey1 approved these changes

2023-04-24 16:34 UTC, andlar approved these changes

2023-04-26 18:45 UTC, merged