OCD-4212 : Removing AQA tests for ONC STAFF and ATL users
chpladmin/chpl-api pull request #1498
Opened 2023-06-01 06:47 UTC by athomas-git

2023-06-01 10:45 UTC, kekey1 submitted a review, later dismissed

2023-06-01 14:39 UTC, ashwinimore requested changes
sent feedback to Anitha to update/remove description in a few tests that refer to 'onc-staff' text

2023-06-01 15:27 UTC, ashwinimore approved these changes

2023-06-01 15:40 UTC, kekey1 approved these changes

2023-06-07 13:50 UTC, kekey1 approved these changes

2023-06-07 15:40 UTC, merged