Ocd 4242
chpladmin/chpl-api pull request #1515
Opened 2023-07-12 02:33 UTC by tmy1313

2023-07-12 14:40 UTC, kekey1 requested changes
Happy to see DTOs deleted. :) And thanks for adding/updating tests!

2023-07-12 14:40 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/TestToolController.java
> +            description = "Returns all of the Test Tools that are currenty in the CHPL.",
```suggestion
            description = "Returns all of the Test Tools that are currently in the CHPL.",
```

2023-07-12 14:40 UTC, kekey1 commented on chpl/chpl-resources/src/main/resources/errors.properties
> +criteriaAttribute.edit.deletedCriteria.listingsExist=This Test Tool and Criteria %s is attested to by %s Listing%s: %s
The name of this error makes me think the text should have '%s' instead of 'Test Tool' so it can be used for other criteria attributes

2023-07-12 14:40 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/criteriaattribute/CriteriaAttribute.java
> +     * TODO: OCD-4242 - Need this text
can you add a checklist item to the ticket for PO to get this text?

2023-07-12 14:40 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/criteriaattribute/CriteriaAttribute.java
> +        return start.isAfter(LocalDate.now()) || end.isBefore(LocalDate.now());
I am looking at this logic... I definitely agree that an attribute is retired if it's end date is before "now", but it seems like "retired" is not the term we would use for the first bit of the boolean logic. If the attribute's start date hasn't happened yet, I don't think we would consider the attribute to be retired. Maybe it doesn't matter for these purposes? But I feel like it's "inactive" or "pending" or some other word besides "retired". Also, I don't see a data-model PR here, but how does the existing test_tool "retired" field fit in here? Should there be an additional PR?

2023-07-12 14:40 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/criteriaattribute/CriteriaAttributeService.java
> +    public void update(CriteriaAttributeSaveContext context) throws EntityRetrievalException{
checkstyle

2023-07-12 14:40 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/criteriaattribute/CriteriaAttributeValidator.java
> +            String message = errorMessageUtil.getMessage("criteriaAttribute.delete.listingsExist",
I had done an update with SVAPs in the past where if there are more than some number of listings (10? 25? i forget) I don't print out the whole list in the error message but instead just give the count. We could end up with thousands of listings in this error message for some values.

2023-07-12 14:40 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/criteriaattribute/CriteriaAttributeValidator.java
> +                                CertificationCriterionService.formatCriteriaNumber(crit),
I think you might want to do the same thing here as above where we don't include the listings at the end of error message if there is more than some set amount. Check SVAP code to see what is currently done there.

2023-07-12 14:40 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/CertificationResultManager.java
> +        testToolNormalizer.normalize(updatedTestTools);
Just wondering about this line. I think by the time this code runs, the normalizer has gone over everything already. It is called in CertifiedProductManager.update() . Can you look into whether/why it needs to be done again here?

2023-07-24 14:13 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/CertificationResultManager.java
> +        testToolNormalizer.normalize(updatedTestTools);
I see that the "normalize" call got moved into the CertificationResultTestToolService, but I'm still wondering why it needs to be called. Does it need to run twice? It should be getting called and running already before this code runs.

2023-07-25 14:41 UTC, kekey1 approved these changes, later dismissed

2023-07-25 15:24 UTC, kekey1 submitted a review, later dismissed

2023-07-25 15:49 UTC, andlar approved these changes, later dismissed
I have a few small changes, but don't think those need to be addressed before we get into testing. I left the comments there so we'll be able to resolve them

2023-07-25 15:49 UTC, andlar commented on chpl/chpl-resources/src/main/resources/errors.properties
> +criteriaAttribute.edit.emptyRequiredDay=Required Day is required.
I think we generally use the word "Date" as our display value for these dates, even though we're using LocalDates with `Day` variable names
```suggestion
criteriaAttribute.edit.emptyStartDay=Start Date is required.
criteriaAttribute.edit.emptyEndDay=End Date is required.
criteriaAttribute.edit.emptyRequiredDay=Required Date is required.
```

2023-07-25 15:49 UTC, andlar commented on chpl/chpl-resources/src/main/resources/errors.properties
> +criteriaAttribute.edit.deletedCriteria.listingsExist=This %s and Criteria %s is attested to by %s Listing%s
I don't like having periods at the ends of things that often show up as bulleted lists, but it seems we've gone down that path
```suggestion
criteriaAttribute.edit.deletedCriteria.listingsExist=This %s and Criteria %s is attested to by %s Listing%s.
```

2023-07-25 15:49 UTC, andlar commented on chpl/chpl-resources/src/main/resources/errors.properties
> +criteriaAttribute.delete.listingsExist=This %s is attested to by %s listing%s
Same "period" thing

```suggestion
criteriaAttribute.delete.listingsExist=This %s is attested to by %s listing%s.
```

2023-07-25 15:49 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/listing/CertificationResultTestToolEntity.java
> +    //@Column(name = "test_tool_id")
Should these be removed? Or restored?

2023-07-25 15:49 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/criteriaattribute/CriteriaAttribute.java
There are some checkstyle issues here related to "TODO:" tags. I know we don't have the text needed for those tags, but also don't want to forget these

2023-08-03 16:57 UTC, kekey1 requested changes

2023-08-03 16:57 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/RuleController.java
> +    public @ResponseBody List<Rule> getAllTestTools() {
```suggestion
    public @ResponseBody List<Rule> getAllRules() {
```

2023-08-03 16:57 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/TestToolController.java
> +    public @ResponseBody List<CertificationCriterion> getCertificationCriteriaForSvap() {
```suggestion
    public @ResponseBody List<CertificationCriterion> getCertificationCriteriaForTestTools() {
```

2023-08-03 16:57 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/criteriaattribute/CriteriaAttributeValidationContext.java
> +    private CriteriaAttribute criteriaAttribe;
```suggestion
    private CriteriaAttribute criteriaAttribute;
```

2023-08-03 17:06 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/criteriaattribute/CriteriaAttribute.java
It appears that all TODO's added as part of this ticket have been addressed.

2023-08-03 17:34 UTC, kekey1 approved these changes, later dismissed

2023-08-03 17:54 UTC, andlar commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/TestToolController.java
> +    public @ResponseBody List<CertificationCriterion> getCertificationCriteriaForSTestTools() {
```suggestion
    public @ResponseBody List<CertificationCriterion> getCertificationCriteriaForTestTools() {
```

Pretty sure this is a typo

2023-08-03 19:44 UTC, andlar submitted a review, later dismissed

2023-08-03 19:46 UTC, kekey1 submitted a review, later dismissed

2023-08-03 20:32 UTC, kekey1 approved these changes

2023-08-03 20:32 UTC, andlar approved these changes

2023-08-04 14:26 UTC, merged