OCD-4305 - Deprecate decertificationDate in favor of decertificationDay
chpladmin/chpl-api pull request #1533
Opened 2023-08-28 14:01 UTC by tmy1313

2023-08-28 14:21 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/CertifiedProductDetailsDTO.java
> +        //this.decertificationDate = entity.getDecertificationDate();
Probably should be updated

2023-08-28 14:26 UTC, kekey1 approved these changes, later dismissed

2023-08-28 16:34 UTC, andlar submitted a review, later dismissed

2023-08-28 17:01 UTC, kekey1 submitted a review, later dismissed

2023-08-29 16:21 UTC, andlar approved these changes, later dismissed

2023-08-29 16:24 UTC, kekey1 requested changes

2023-08-29 16:24 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/CertifiedProductSearchBasicDetails.java
> +    @Schema(description = "Decertification day")
Missing some annotations here for JSON serialization

2023-08-29 17:03 UTC, kekey1 approved these changes

2023-08-29 19:28 UTC, andlar approved these changes

2023-09-07 18:24 UTC, merged