OCD-4336: Add 2 new criteria
chpladmin/chpl-api pull request #1554
Opened 2023-10-10 16:18 UTC by kekey1

2023-10-18 16:05 UTC, andlar approved these changes, later dismissed

2023-10-19 13:43 UTC, tmy1313 requested changes

2023-10-19 13:43 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/compliance/surveillance/SurveillanceDAO.java
>                  .toList();
Based on OCD-4308, I don't think this is correct.  The list of requirements and non-conformities is based on the Surveillance Start Date.  We need to send all of the requirements and non-conformities to the front end and then on the front end we will do the correct filtering.

2023-10-19 13:59 UTC, tmy1313 approved these changes, later dismissed

2023-10-27 19:57 UTC, andlar submitted a review, later dismissed

2023-11-06 20:36 UTC, andlar approved these changes, later dismissed

2023-11-07 18:47 UTC, andlar submitted a review, later dismissed

2023-11-09 16:26 UTC, andlar submitted a review, later dismissed

2023-11-14 16:17 UTC, tmy1313 approved these changes, later dismissed

2023-11-15 14:45 UTC, andlar approved these changes

2023-11-15 14:48 UTC, tmy1313 approved these changes

2023-11-15 15:07 UTC, merged