OCD-4203 - Implement basic Cognito authentication/authorization
chpladmin/chpl-api pull request #1565
Opened 2023-11-02 02:15 UTC by tmy1313

2023-11-03 14:51 UTC, kekey1 requested changes

2023-11-03 14:51 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/UserManagementController.java
> +            return cognitoAuthenticationManager.getUserInfo("tmy1313@gmail.com");
Do you want yourself hardcoded in here?

2023-11-03 14:51 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/FeatureList.java
> +    public static final String SSO = "sso";
Make sure to add this to all environments (I happened to look at prod and did not see it there)

2023-11-03 14:51 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/auth/authentication/CognitoJwtUserConverter.java
> +        //decodeJwt.getClaims().entrySet().stream()
keep? delete?

2023-11-03 14:51 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/auth/jwt/CognitoRsaKeyProvider.java
> +        String url = String.format("https://cognito-idp.%s.amazonaws.com/%s/.well-known/jwks.json", awsCognitoRegion, awsUserPoolId);
It feels like some of this should be in an environment property or at least a constant

2023-11-04 10:53 UTC, kekey1 approved these changes, later dismissed

2023-11-04 10:53 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/auth/authentication/CognitoJwtUserConverter.java
> +    private String tokenizezRsaKeyUrl;
Is this the right word here or is it a typo? Genuine question. I feel like there is an extra "z" or is it spelled that way on purpose like we might do with "clazz" ?

2023-11-06 12:48 UTC, andlar submitted a review, later dismissed

2023-11-14 14:32 UTC, andlar approved these changes, later dismissed

2023-11-14 14:37 UTC, kekey1 requested changes

2023-11-14 14:37 UTC, kekey1 commented on chpl/chpl-resources/src/main/resources/environment.properties
> +download2015Hour=15
I don't think we need this? We don't create a 2015 file anymore

2023-11-14 14:40 UTC, kekey1 approved these changes

2023-11-14 14:41 UTC, andlar approved these changes

2023-11-14 14:43 UTC, merged