OCD-4333 - Add Standards attribute to criteria
chpladmin/chpl-api pull request #1568
Opened 2023-11-07 14:36 UTC by tmy1313

2023-11-07 15:16 UTC, andlar reviewed
I don't know where it should be, but do we need to add something to the upload parser to put the expected column heading for the new "STANDARD" field that our upload template will use? It could easily be here already, but I don't know where to look

2023-11-07 15:16 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/dao/CertificationCriterionAttributeDAO.java
> +                .filter(att -> att.getStandard())
Should this be in a different function? Something looks odd here

2023-11-07 15:16 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/CertificationResult.java
> +    // TODO - Need this text for OCD-4333
Either we need this text, or the TODO should be removed

2023-11-07 15:16 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/xmlgenerator/CertificationResultStandardXmlGenerator.java
Checkstyle issue

2023-11-15 17:53 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/CertificationResult.java
> +    // TODO - Need this text for OCD-4333
A checklist item exists xsd/json documentation exists on the ticket

2023-11-15 18:01 UTC, andlar submitted a review, later dismissed

2023-11-15 20:10 UTC, kekey1 approved these changes, later dismissed

2023-11-20 21:08 UTC, andlar approved these changes, later dismissed

2023-11-21 11:28 UTC, kekey1 approved these changes, later dismissed

2023-11-21 11:28 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/upload/listing/ListingConfirmationManager.java
> +            saveStandard(certResult);
Should be plural

2023-11-27 20:44 UTC, andlar approved these changes, later dismissed

2023-12-04 18:03 UTC, andlar submitted a review, later dismissed

2023-12-04 18:16 UTC, kekey1 approved these changes

2023-12-05 12:00 UTC, kekey1 requested changes

2023-12-05 12:00 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/standard/StandardDAO.java
> +                            + "FROM StandardEntity s "
Need to LEFT JOIN FETCH s.rule. Check below methods with HQL as well.

2023-12-05 18:20 UTC, kekey1 approved these changes, later dismissed

2023-12-05 19:08 UTC, andlar submitted a review, later dismissed

2023-12-05 19:51 UTC, kekey1 approved these changes, later dismissed

2023-12-05 19:54 UTC, andlar approved these changes, later dismissed

2023-12-05 21:46 UTC, andlar approved these changes

2023-12-06 11:49 UTC, kekey1 approved these changes

2023-12-06 15:07 UTC, merged