OCD-4408 - Require ONC-ACB to enter at least one Standard per Standards 'group'
chpladmin/chpl-api pull request #1588
Opened 2023-12-12 19:57 UTC by tmy1313

2023-12-12 20:40 UTC, andlar requested changes

2023-12-12 20:40 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/standard/Standard.java
> +    @XmlTransient
This might mean that this ticket is either blocking, or blocked by, OCD-4294

2023-12-12 20:40 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/reviewer/edition2015/StandardAllowedByCriteriaReviewer.java
> +                        listing.addBusinessErrorMessage("Exactly one of the following standards must be selected: " +
```suggestion
                        listing.addBusinessErrorMessage("At least one of the following standards must be selected: " +
```

2023-12-12 20:40 UTC, andlar commented on chpl/chpl-service/src/test/java/gov/healthit/chpl/upload/listing/ListingUploadManagerTest.java
Is it possible to add a test for "grouped standards" to expect at least one of a group to be uploaded? I don't know if we have the data for it, but wanted to ask

2023-12-13 16:01 UTC, kekey1 requested changes

2023-12-13 16:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/standard/Standard.java
> +    @XmlTransient
It's a merge conflict for sure but I'm not sure it's blocked. Even if we forgot to remove the XmlTransient annotation it wouldn't make any functional difference.

2023-12-13 16:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/validation/listing/reviewer/edition2015/StandardAllowedByCriteriaReviewer.java
> +                        listing.addBusinessErrorMessage("Exactly one of the following standards must be selected: " +
checkstyle, and also, can this be a message gotten from errors.properties ?

2023-12-15 19:41 UTC, andlar submitted a review, later dismissed

2023-12-20 14:39 UTC, kekey1 approved these changes, later dismissed

2023-12-21 14:10 UTC, andlar submitted a review, later dismissed

2023-12-21 18:34 UTC, andlar submitted a review, later dismissed

2023-12-21 18:43 UTC, kekey1 submitted a review, later dismissed

2024-01-03 15:12 UTC, kekey1 approved these changes, later dismissed

2024-01-03 15:12 UTC, andlar submitted a review, later dismissed

2024-01-18 14:47 UTC, andlar approved these changes

2024-01-18 14:54 UTC, kekey1 approved these changes

2024-01-24 14:37 UTC, merged