OCD-4379 - Add ROLE_ONC, ROLE_DEVELOPER, ROLE_ACB
chpladmin/chpl-api pull request #1605
Opened 2024-02-05 18:46 UTC by tmy1313

2024-02-09 18:23 UTC, kekey1 approved these changes, later dismissed

2024-02-09 18:23 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/CHPLHttpSecurityConfig.java
> +        private JWTUserConverterFacade userConverterFactory;
```suggestion
        private JWTUserConverterFacade userConverterFacade;
```

2024-02-09 18:23 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/scheduler/CreateOneTimeTriggerActionPermissions.java
> +            LOGGER.info("User is Admin");
some debug code here

2024-02-09 18:23 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/util/AuthUtil.java
> +        //if (auth.getPrincipal() instanceof UserDetails) {
remove commented-out code

2024-02-09 18:23 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/util/CognitoAuthUtil.java
> +import gov.healthit.chpl.auth.user.JWTAuthenticatedUser;
checkstyle - duplicate import

2024-02-13 12:13 UTC, kekey1 requested changes

2024-02-13 12:13 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/permissions/domains/scheduler/CreateOneTimeTriggerActionPermissions.java
> +        if (AuthUtil.getCurrentUser() != null) {
Oh, checkstyle called this out - an "if" with nothing inside. Is this correct?

2024-02-14 14:37 UTC, kekey1 approved these changes, later dismissed

2024-02-14 15:15 UTC, andlar submitted a review, later dismissed

2024-02-14 21:15 UTC, kekey1 approved these changes, later dismissed

2024-02-15 14:26 UTC, andlar approved these changes, later dismissed

2024-02-27 14:31 UTC, andlar submitted a review, later dismissed

2024-02-28 13:25 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/auth/authentication/JWTUserConverterFacade.java
> +        if (ff4j.check(FeatureList.SSO)) {
Does this mean we cannot impersonate, at all, if the SSO flag is on? I know we're not turning it on in PROD, but I thought we were leaving it on in DEV/QA/STG for burn-in / testing purposes. If that's the case, we've basically turned off impersonation

2024-02-28 19:07 UTC, andlar submitted a review, later dismissed

2024-03-01 13:53 UTC, andlar approved these changes, later dismissed

2024-03-07 16:07 UTC, andlar approved these changes

2024-03-12 13:48 UTC, kekey1 approved these changes

2024-03-12 14:37 UTC, merged