OCD-4482 - Code Set Indicators Update Feature
chpladmin/chpl-api pull request #1613
Opened 2024-02-15 17:55 UTC by tmy1313

2024-02-21 18:01 UTC, kekey1 requested changes

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CodeSetController.java
> +    @Operation(summary = "Retrieve all Code Set Dates. ",
do we want to update the language here? "Retrieve all Code Sets" rather than "Code Set Dates"

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CodeSetController.java
> +            description = "Returns all of the Code Set Dates that are currently in the CHPL.",
Same comment, it' s in a number of places in the endpoint documentation in this file. I won't comment on them all.

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/codeset/CertificationResultCodeSet.java
> +    @Schema(description = "Code set internal ID")
i don't think this description is right, this is not an "id"

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/codeset/CodeSetDAO.java
> +                        + "AND (csd.id = :entityid) ",
Does this work? I don't see an entity aliased with "csd" in the HQL

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/codeset/CodeSetManager.java
> +    //        + "T(gov.healthit.chpl.permissions.domains.FunctionalityTestedDomainPermissions).UPDATE)")
remove commented out code... but actually this probably needs some permissions applied to it

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/codeset/CodeSetManager.java
> +    @GenerateListingDownloadFile(listingSet = {ListingSet.EDITION_2011, ListingSet.EDITION_2014, ListingSet.INACTIVE})
do we really have to generate the 2011 and 2014 download files here? I am not aware of any of those having code sets

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/codeset/CodeSetManager.java
> +    //        + "T(gov.healthit.chpl.permissions.domains.FunctionalityTestedDomainPermissions).CREATE)")
same comment to apply permissions to this code set operation

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/codeset/CodeSetManager.java
> +    //        + "T(gov.healthit.chpl.permissions.domains.FunctionalityTestedDomainPermissions).DELETE)")
permissions

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/codeset/CodeSetValidator.java
> +                messages.add(errorMessageUtil.getMessage("codeSet.edit.duplicate", "Code Set Date"));
```suggestion
                messages.add(errorMessageUtil.getMessage("codeSet.edit.duplicate", "Code Set"));
```

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/codeset/CodeSetValidator.java
> +            messages.add(errorMessageUtil.getMessage("codeSet.edit.duplicate", "Code Set Date"));
```suggestion
            messages.add(errorMessageUtil.getMessage("codeSet.edit.duplicate", "Code Set"));
```

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/CertificationResult.java
> +    @Schema(description = "Need this text")
I think we are supposed to try to put something here to save time for the PO

2024-02-21 18:01 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/CertificationResult.java
> +    private List<CertificationResultCodeSet> codeSets = new ArrayList<CertificationResultCodeSet>();
Not on this line - but I think you might need to initialize this variable in the no-args constructor below (it has no change so I don't think I can leave a comment on the line in question - but around line 230). That was an issue I ran into in the Standards ticket

2024-02-21 19:10 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/domain/CertificationResult.java
> +    private List<CertificationResultCodeSet> codeSets = new ArrayList<CertificationResultCodeSet>();
Not sure I understand this problem.  Why would we need to initialize in the default constructor, when the definition of the attribute has an initialization.

2024-02-22 15:33 UTC, kekey1 approved these changes

2024-02-22 16:19 UTC, andlar approved these changes

2024-02-29 14:59 UTC, merged