OCD-4492 - Update Jobs to incorporate Cognito users
chpladmin/chpl-api pull request #1641
Opened 2024-04-22 02:33 UTC by tmy1313

2024-04-22 17:04 UTC, kekey1 requested changes

2024-04-22 17:04 UTC, kekey1 commented on chpl/chpl-resources/src/main/resources/jobs.xml
> +                    <value>ROLE_ADMIN;ROLE_ONC;ROLE_ACB;;chpl-admin;chpl-onc;chpl-onc-acb</value>
```suggestion
                    <value>ROLE_ADMIN;ROLE_ONC;ROLE_ACB;chpl-admin;chpl-onc;chpl-onc-acb</value>
```

2024-04-22 17:04 UTC, kekey1 commented on chpl/chpl-resources/src/main/resources/jobs.xml
> +                    <value>ROLE_ADMIN;ROLE_ACB;chpl-admin;chpl-onc</value>
```suggestion
                    <value>ROLE_ADMIN;ROLE_ACB;chpl-admin;chpl-onc-acb</value>
```

2024-04-23 14:04 UTC, kekey1 submitted a review, later dismissed

2024-04-23 14:09 UTC, andlar submitted a review, later dismissed

2024-05-02 20:05 UTC, andlar approved these changes

2024-05-06 16:23 UTC, kekey1 approved these changes

2024-05-06 18:41 UTC, merged