OCD-4237 - Upgrade Spring Framework
chpladmin/chpl-api pull request #1656
Opened 2024-05-20 17:45 UTC by tmy1313

2024-05-25 11:39 UTC, kekey1 submitted a review, later dismissed

2024-05-25 11:39 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/filter/DeprecatedEndpointUsageFilter.java
> +        //if (!ServletRequestPathUtils.hasParsedRequestPath(request)) {
Can this be removed?

2024-05-25 11:39 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/filter/DeprecatedEndpointUsageFilter.java
> +        //Set<String> matchingUrlPatterns = requestMapping.getPatternsCondition().getPatterns();
Remove?

2024-05-25 11:39 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/annotation/CacheControlHandlerInterceptor.java
> +        //return super.preHandle(request, response, handler);
Remove?

2024-05-25 11:39 UTC, kekey1 commented on chpl/chpl-service/pom.xml
> +        <!--
Can this be deleted?

2024-05-25 11:39 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/datatypes/JsonPostgreSQLDialect.java
> +//public class JsonPostgreSQLDialect extends PostgreSQLDialect {
Can we delete this file?

2024-05-25 11:39 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/scheduler/job/onetime/FixupDeveloperAttestationActivityJob.java
> +import jakarta.persistence.Query;
Could we delete this job instead? And any other onetime jobs?

2024-05-29 13:56 UTC, kekey1 submitted a review, later dismissed

2024-05-29 14:42 UTC, andlar submitted a review, later dismissed

2024-05-30 14:06 UTC, kekey1 approved these changes

2024-05-30 16:49 UTC, andlar submitted a review, later dismissed

2024-06-25 12:44 UTC, kekey1 reviewed
I think this needs a change in SearchDevelopersController. Can you check out the feature branch and make sure it compiles?

2024-06-25 12:44 UTC, kekey1 requested changes
I think this needs a change in SearchDevelopersController. Can you check out the feature branch and make sure it compiles?

2024-06-25 17:11 UTC, andlar approved these changes

2024-06-25 17:17 UTC, kekey1 approved these changes

2024-06-25 17:58 UTC, merged