OCD-4602 - Allow newly created user to change their password when logging in
chpladmin/chpl-api pull request #1670
Opened 2024-06-20 15:26 UTC by tmy1313

2024-06-24 16:34 UTC, andlar submitted a review, later dismissed

2024-06-24 18:16 UTC, kekey1 submitted a review, later dismissed

2024-06-24 18:16 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/PasswordGenerator.java
> +        String upperCaseLetters = RandomStringUtils.random(2, 65, 90, true, true);
just noting there are a number of checkstyle magic-number things here. Can we make some of them constants?

2024-07-08 14:03 UTC, kekey1 approved these changes, later dismissed

2024-07-09 12:29 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/PasswordGenerator.java
> +    private static final int MAX_UPPER_CASE_LETTER = 65;
Shouldn't these be different values?

2024-07-09 18:43 UTC, andlar requested changes
Need to update the constants before this can be merged

2024-07-10 15:46 UTC, andlar approved these changes

2024-07-10 16:03 UTC, kekey1 approved these changes

2024-07-12 13:59 UTC, merged