OCD-4615 - Forgot password functionality for Cognito Users
chpladmin/chpl-api pull request #1678
Opened 2024-07-08 14:29 UTC by tmy1313

2024-07-23 15:31 UTC, kekey1 requested changes

2024-07-23 15:31 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/user/cognito/password/CognitoForgotPassword.java
> +    private static final Long MILLIS_IN_HOUR = 24L * 60L * 60L * 1000L;
The variable says milliseconds in an hour, but I think the numbers equal milliseconds in a day? Not sure which is correct.

2024-07-25 15:18 UTC, kekey1 submitted a review, later dismissed

2024-07-25 17:20 UTC, andlar submitted a review, later dismissed

2024-08-05 10:54 UTC, andlar submitted a review, later dismissed

2024-08-05 15:17 UTC, andlar approved these changes

2024-08-08 15:54 UTC, merged