OCD-4545 - Edit Cognito user information
chpladmin/chpl-api pull request #1682
Opened 2024-07-15 14:19 UTC by tmy1313

2024-07-15 18:08 UTC, kekey1 requested changes

2024-07-15 18:08 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/user/cognito/CognitoUpdateUserValidator.java
> +            validationErrors.add(msgUtil.getMessage("cognito.user.create.fullName.empty"));
I expected to see a change in errors.properties for this, but it's not showing that file changed

2024-07-15 18:08 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CognitoUserController.java
> +    @RequestMapping(value = "/{ssoUserId}", method = RequestMethod.PUT, consumes = MediaType.APPLICATION_JSON_VALUE, produces = "application/json; charset=utf-8")
I notice in some other code the variable is called cognitoUserId instead of ssoUserId. I was just wondering which we are going with. And also maybe we don't need this in the request mapping at all? It doesn't look like it's used.

2024-07-16 15:47 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/user/cognito/CognitoUpdateUserValidator.java
> +            validationErrors.add(msgUtil.getMessage("cognito.user.create.fullName.empty"));
This is an existing message and did not need to be added.

2024-07-16 16:15 UTC, kekey1 approved these changes

2024-07-16 17:28 UTC, andlar approved these changes

2024-07-31 19:12 UTC, merged