OCD-4641: Validation for duplicate product, version names
chpladmin/chpl-api pull request #1690
Opened 2024-08-01 21:07 UTC by kekey1

2024-08-02 14:37 UTC, andlar submitted a review, later dismissed

2024-08-05 14:47 UTC, tmy1313 approved these changes, later dismissed

2024-08-19 17:49 UTC, andlar submitted a review, later dismissed

2024-08-21 15:34 UTC, tmy1313 requested changes

2024-08-21 15:34 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/ProductManager.java
> +                    productsBeingMerged,msgUtil);
Checkstyle issue

2024-08-22 13:24 UTC, tmy1313 approved these changes

2024-08-26 11:21 UTC, andlar approved these changes

2024-08-26 13:04 UTC, merged