Ocd 4668
chpladmin/chpl-api pull request #1711
Opened 2024-09-17 18:05 UTC by tmy1313

2024-09-24 13:06 UTC, kekey1 requested changes

2024-09-24 13:06 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/report/surveillance/SurveillanceReportsService.java
> +                                "Active",
Can you use the CertificationStatusType enum here instead of these strings?

2024-09-24 13:06 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/report/surveillance/SurveillanceReportsService.java
> +                                "Active",
Same comment about CertificationStatusType

2024-09-24 13:49 UTC, kekey1 approved these changes, later dismissed

2024-09-24 14:57 UTC, andlar approved these changes, later dismissed

2024-09-27 14:18 UTC, andlar approved these changes

2024-09-30 14:04 UTC, kekey1 approved these changes

2024-10-01 13:20 UTC, merged