feat: add new endpoints to add organizations to an existing user
chpladmin/chpl-api pull request #1732
Opened 2024-10-29 13:16 UTC by tmy1313

OCD-4721

2024-11-07 20:19 UTC, kekey1 submitted a review, later dismissed

2024-11-07 20:19 UTC, kekey1 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/UserManagementController.java
> +            description = "Gives the user permission on the object in the invitation (usually an additional ACB or Developer)."
I think this documentation is copied from the CHPL-login workflow methods. The line about which endpoints to call in which order is not right for the Cognito methods. Can you check the other Cognito auth methods as well? They are not currently in the diff but it looks like they might have the same documentation.

2024-11-07 20:19 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/user/cognito/CognitoApiWrapper.java
> +    public User getUserByPassingCognitoUserAttributeCache(String accessToken) throws UserRetrievalException {
When I first read this method name I thought it was two words "by passing" but I think it's meant as one word "bypassing" - can you change the camelcase to make this clear? getUserBypassingCognitoUserAttributeCache, or maybe even simpler getUserNoCache?

2024-11-25 20:36 UTC, kekey1 requested changes

2024-11-25 20:36 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/user/cognito/CognitoApiWrapper.java
> +<<<<<<< Updated upstream
Merge issue

2024-11-26 11:07 UTC, kekey1 requested changes

2024-11-26 11:07 UTC, kekey1 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/user/cognito/CognitoApiWrapper.java
> +    @CacheEvict(value = CacheNames.COGNITO_USERS, key = "#user.cognitoId")
It looks like we cache users both with UUID as a key and email as a key (see above method `getUserInfo(String email)`). But here we are evicting only the UUID key. I'm not 100% sure I'm correct but I think so... can you check on this?

2024-12-02 17:06 UTC, kekey1 approved these changes, later dismissed

2024-12-02 17:37 UTC, andlar submitted a review, later dismissed

2024-12-10 14:29 UTC, kekey1 approved these changes

2024-12-10 15:09 UTC, andlar approved these changes

2024-12-11 15:01 UTC, merged