feat!: Add ability to "includeDisabled" to all calls that get users
chpladmin/chpl-api pull request #1733
Opened 2024-10-30 11:23 UTC by kekey1

The parameter will only take effect if the user is ADMIN or ONC. Otherwise only Active users will be returned and the parameter will be ignored.

[#OCD-4713]

2024-10-31 11:29 UTC, andlar submitted a review, later dismissed

2024-11-04 02:39 UTC, tmy1313 requested changes

2024-11-04 02:39 UTC, tmy1313 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/CertificationBodyController.java
> +            @RequestParam(value = "includeDisabled", required = false, defaultValue = "false") String includeDisabled)
Shouldn't this be a `boolean`?

2024-11-04 02:39 UTC, tmy1313 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/DeveloperController.java
> +        @RequestParam(value = "includeDisabled", required = false, defaultValue = "false") String includeDisabled)
Shouldn't this be a `boolean`?

2024-11-04 02:39 UTC, tmy1313 commented on chpl/chpl-api/src/main/java/gov/healthit/chpl/web/controller/UserManagementController.java
> +            @RequestParam(value = "includeDisabled", required = false, defaultValue = "false") String includeDisabled) {
Shouldn't this be a `boolean`?

2024-11-04 02:39 UTC, tmy1313 commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/manager/auth/UserManager.java
> +        if (includeDisabled == null || BooleanUtils.isFalse(includeDisabled)) {
Do we need to use `BooleanUtils`?  Also, in couple other places.

2024-11-05 14:35 UTC, tmy1313 approved these changes, later dismissed

2024-11-05 14:43 UTC, andlar approved these changes, later dismissed

2024-11-12 17:54 UTC, andlar submitted a review, later dismissed

2024-11-13 18:09 UTC, andlar approved these changes

2024-11-14 17:43 UTC, tmy1313 approved these changes

2024-11-14 17:46 UTC, merged