OCD-3154: Check for duplicate data on confirm and edit
chpladmin/chpl-api pull request #956
Opened 2020-05-26 10:51 UTC by kekey1

2020-05-26 11:35 UTC, andlar submitted a review, later dismissed

2020-05-27 14:28 UTC, tmy1313 requested changes

2020-05-27 14:28 UTC, tmy1313 commented on chpl/chpl-service/src/test/java/gov/healthit/chpl/validation/listing/reviewer/duplicate/AtlDuplicateReviewerTest.java
> +        MockitoAnnotations.initMocks(this);
Not sure that this is necessary, since there are not Mockito annotation on any of the classes private members.

2020-05-27 14:28 UTC, tmy1313 commented on chpl/chpl-service/src/test/java/gov/healthit/chpl/validation/listing/reviewer/duplicate/IcsSourceDuplicateReviewerTest.java
> +        MockitoAnnotations.initMocks(this);
Same as above.  I won't note any other instances.

2020-05-27 16:53 UTC, andlar submitted a review, later dismissed

2020-05-28 14:01 UTC, tmy1313 submitted a review, later dismissed

2020-06-16 12:59 UTC, andlar submitted a review, later dismissed

2020-06-24 15:16 UTC, andlar submitted a review, later dismissed

2020-06-29 21:15 UTC, andlar submitted a review, later dismissed

2020-07-08 22:04 UTC, andlar submitted a review, later dismissed

2020-07-10 11:22 UTC, andlar approved these changes

2020-07-15 13:55 UTC, Plow74 approved these changes

2020-07-15 13:58 UTC, merged