OCD-3395: Developer Access Report
chpladmin/chpl-api pull request #997
Opened 2020-07-31 18:21 UTC by kekey1

2020-08-03 12:24 UTC, andlar requested changes

2020-08-03 12:24 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/dto/ApiKeyDTO.java
> -        return Util.getNewDate(creationDate);
I think this line might need to be restored. Not sure exactly what the function does, or if it's actually needed, but using the Lombok thing would change functionality. Same thing with the other dates

2020-08-03 12:24 UTC, andlar commented on chpl/chpl-service/src/main/java/gov/healthit/chpl/entity/ApiKeyEntity.java
> -        return Util.getNewDate(creationDate);
Similar thing to the DTO date thing

2020-08-03 13:18 UTC, andlar submitted a review, later dismissed

2020-08-03 20:53 UTC, tmy1313 submitted a review, later dismissed

2020-08-12 14:56 UTC, andlar approved these changes

2020-08-13 14:06 UTC, tmy1313 approved these changes

2020-08-13 14:13 UTC, merged